### ISSUE TITLE
sat fetch issue

### ISSUE THREAD

**Issue by xfwangnoaa** [sat-utils/sat-fetch#10]
installation failed 

pipenv install sat-fetch
Installing sat-fetch…
Error:  An error occurred while installing sat-fetch!
Error text: Collecting sat-fetch
  Using cached sat-fetch-0.1.0rc2.tar.gz (5.4 kB)
Collecting sat-search~=0.2.2
  Using cached sat-search-0.2.3.tar.gz (10 kB)
Collecting gippy~=1.0.3
  Using cached gippy-1.0.3.tar.gz (646 kB)
Collecting sat-fetch
  Using cached sat-fetch-0.1.0rc1.tar.gz (5.2 kB)

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xfwan\.virtualenvs\explore-sat-util-h-J491rL\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xfwan\\AppData\\Local\\Temp\\pip-install-exsg32kw\\gippy_dd24cc6d96c64af1b719306751be356e\\setup.py'"'"'; __file__='"'"'C:\\Users\\xfwan\\AppData\\Local\\Temp\\pip-install-exsg32kw\\gippy_dd24cc6d96c64af1b719306751be356e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xfwan\AppData\Local\Temp\pip-pip-egg-info-rcra27p0'
         cwd: C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\
    Complete output (24 lines):
    C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py:34: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      from imp import load_source
    Traceback (most recent call last):
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py", line 71, in get
        stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
      File "c:\program files\python37\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "c:\program files\python37\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py", line 178, in <module>
        gdal_config = CConfig(os.environ.get('GDAL_CONFIG', 'gdal-config'))
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py", line 64, in __init__
        self.get_include()
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py", line 86, in get_include
        for item in self.get('--cflags').split():
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\gippy_dd24cc6d96c64af1b719306751be356e\setup.py", line 74, in get
        raise OSError("Could not find script")
    OSError: Could not find script
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c4/58/c79b0213b3a601a5d921f00fc1b3b443edd4c31882d7f69271c793125d9c/gippy-1.0.3.tar.gz#sha256=193603f83b37563a69aca7a60b17fe6093dc981b4466e9f69f8aa73993c26439 (from https://pypi.org/simple/gippy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xfwan\.virtualenvs\explore-sat-util-h-J491rL\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xfwan\\AppData\\Local\\Temp\\pip-install-exsg32kw\\sat-fetch_b43e0bcee4404deda11ecbf15e077402\\setup.py'"'"'; __file__='"'"'C:\\Users\\xfwan\\AppData\\Local\\Temp\\pip-install-exsg32kw\\sat-fetch_b43e0bcee4404deda11ecbf15e077402\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xfwan\AppData\Local\Temp\pip-pip-egg-info-e0sx6moy'
         cwd: C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\sat-fetch_b43e0bcee4404deda11ecbf15e077402\
    Complete output (7 lines):
    C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\sat-fetch_b43e0bcee4404deda11ecbf15e077402\setup.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      from imp import load_source
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xfwan\AppData\Local\Temp\pip-install-exsg32kw\sat-fetch_b43e0bcee4404deda11ecbf15e077402\setup.py", line 12, in <module>
        with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xfwan\\AppData\\Local\\Temp\\pip-install-exsg32kw\\sat-fetch_b43e0bcee4404deda11ecbf15e077402\\requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bf/5f/b9b04a7f92a97ae4f1938067f100da6a217ff41375a4d659dcf23b276688/sat-fetch-0.1.0rc1.tar.gz#sha256=da9d49944abe7579763b255414db2ea1f7cbfcf575524ae19e196fd1ac01a747 
(from https://pypi.org/simple/sat-fetch/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement gippy~=1.0.3 (from sat-fetch)
ERROR: No matching distribution found for gippy~=1.0.3

This is likely caused by a bug in sat-fetch. Report this to its maintainers.
Installation Failed

**Comment by xfwangnoaa** [comment]
is requirements.txt required for the installation?
